# Basic site settings
title: Marrese & Wisky
email: contato@marresewisky.adv.br
description: ""
lang: pt-BR

# Site URLs
baseurl: ""
url: https://marresewisky.adv.br/

# Sass settings
sass:
  style: compressed
  quiet_deps: true

# Jekyll plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Files to exclude from the final output
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md