# Basic site settings
title: Marrese & Wisky
email: contato@marresewisky.adv.br
description: ""

# Site URLs
baseurl: ""
url: ""

# Sass settings
sass:
  style: compressed

# Jekyll plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Files to exclude from the final output
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md