# Basic site settings
title: Marrese, Wisky & Maia
email: contato@marresewisky.adv.br
description: ""
lang: pt-BR

# Site URLs
baseurl: ""
url: https://marresewisky.adv.br/

# --- footer social media links --- #
social-network-links:
  - name: "Me mande um e-mail"
    url: "mailto:email@email.com"
    icon: "bi bi-envelope"
  - name: "Instagram"
    url: "https://github.com/danielwisky"
    icon: "bi bi-instagram"
  - name: "LinkedIn"
    url: "https://www.linkedin.com/in/danielwisky"
    icon: "bi bi-linkedin"

# Sass settings
sass:
  style: compressed

# Jekyll plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Files to exclude from the final output
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md